#docker run --name world_db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql
version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .


  # db is is db folder

  db:
    build: world/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    # This tells docker to forward requests from our local machine on port 33060 to port 3306 inside the docker container.
    # We can now connect locally without having to do so from another docker container.
          - "33060:3306"